version: 2
jobs:
  build:
    branches:
      only:
        - master
        - develop
        - '/ft-.*/'
        - '/ch-.*/'
        - '/bg-.*/'
    docker:
      - image: 'circleci/node:10.15.0'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: 'yarn install'
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: 'Setup Code Climate test-reporter'
          command: "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter\nchmod +x ./cc-test-reporter\n"
      - run:
          name: 'yarn coveralls'
          command: "./cc-test-reporter before-build\nyarn coveralls\n./cc-test-reporter after-build --coverage-input-type clover --exit-code $?\n"
